ci:
    autofix_commit_msg: |
        chore(pre-commit.ci): auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: "chore/pre-commit-ci-update-config"
    autoupdate_commit_msg: "chore(pre-commit.ci): pre-commit autoupdate"
    autoupdate_schedule: weekly

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-yaml
          - id: check-toml
          - id: check-vcs-permalinks
          - id: end-of-file-fixer
            exclude: |
                (?x)^(
                    .*\.py\.jinja|
                    .*\.raw
                )$
          - id: trailing-whitespace
            exclude: |
              (?x)^(
                .*\.ambr|
                .*\.raw
              )$
          - id: mixed-line-ending
            args: [--fix=lf]
    - repo: https://github.com/grantjenks/blue.git
      rev: v0.9.0
      hooks:
      - id: blue
